name: edcode_streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - openpyxl
  - plotly
  - pip:
      - streamlit
      - openai
      - sentence-transformers

